model_params:
  name: "BetaVAE"
  latent_dim: 4
  loss_type: "B"
  beta: 0.1
  encoder:
    in_channels: 3
    base_dim: 8
    scales: 4
    num_blocks: 1
    channel_multiplier: 2
    transpose: False
    kernel_size: 5
    residual: True
    bottleneck: True
    weight_norm: False
    norm: "layer"
    activation: "silu"
  decoder:
    out_dim: 3
    scales: 4
    num_blocks: 1
    channel_multiplier: 0.5
    transpose: True
    kernel_size: 5
    residual: True
    bottleneck: True
    weight_norm: False
    norm: "layer"
    activation: "silu"
    final_activation: "sigmoid"

data_params:
  dataset: "celeba"
  data_path: "/mnt/ext-data-01/data"
  train_batch_size: 64
  val_batch_size: 64
  patch_size: 64
  num_workers: 4
  pin_memory: True

experiment_params:
  optim1:
    lr: 0.0005
    weight_decay: 0.001
    warmup_epochs: 5
  manual_seed: 1265
  metrics: ["lpips", "ssim", "psnr", "fid"]

trainer_params:
  devices: 1
  strategy: "ddp"
  precision: "32-true"
  gradient_clip_val: 5.0
  gradient_clip_algorithm: norm
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "BetaVAE"
