model_params:
  name: "ConditionedVAE"
  latent_dim: 4
  cond_weight: 10
  identity_model_path: "magface_r18.pth"
  residual_type: sech
  C_type: exp
  gamma: 0.1
  max_capacity: 50
  C_stop_epoch: 60
  learn_log_sigma: False
  encoder:
    in_channels: 3
    base_dim: 8
    scales: 4
    num_blocks: 1
    channel_multiplier: 2
    transpose: False
    kernel_size: 5
    residual: True
    bottleneck: True
    weight_norm: False
    norm: "layer"
    activation: "silu"
  mixer:
    scales: 1
    num_blocks: 4
    channel_multiplier: 1
    transpose: True
    kernel_size: 5
    residual: True
    bottleneck: True
    weight_norm: False
    norm: "layer"
    activation: "silu"
    cond_dim: 512
    mix_type: "adain"
  decoder:
    out_dim: 3
    scales: 3
    num_blocks: 2
    channel_multiplier: 0.5
    transpose: True
    kernel_size: 5
    residual: True
    bottleneck: True
    weight_norm: False
    norm: "layer"
    activation: "silu"
    final_activation: "sigmoid"

data_params:
  dataset: "celeba"
  data_path: "/mnt/ext-data-01/data"
  train_batch_size: 64
  val_batch_size: 64
  patch_size: 64
  num_workers: 4
  pin_memory: True

experiment_params:
  optim1:
    lr: 0.0005
    weight_decay: 0.001
    warmup_epochs: 10
  manual_seed: 1265
  metrics: ["lpips", "ssim", "psnr", "fid"]
  clip_gradient: True
  gradient_clip_val: 5.0
  gradient_clip_algorithm: norm

trainer_params:
  devices: 1
  strategy: "ddp"
  precision: "32-true"
  max_epochs: 200

logging_params:
  save_dir: "logs/"
  name: "ConditionedVAE"
