model_params:
  name: "FlowVAE"
  latent_dim: 32
  flow_type: nice
  flow_length: 8
  encoder:
    in_channels: 3
    in_size: 64
    base_dim: 8
    scales: 4
    num_blocks: 1
    channel_multiplier: 2
    min_spatial: 4
    residual: True
    bottleneck: True
    weight_norm: False
    norm: "layer"
    activation: "silu"
  decoder:
    out_channels: 3
    scales: 4
    num_blocks: 1
    channel_multiplier: 0.5
    residual: True
    bottleneck: True
    weight_norm: False
    norm: "layer"
    activation: "silu"
    final_activation: "sigmoid"

data_params:
  dataset: "celeba"
  data_path: "/mnt/ext-data-01/data"
  train_batch_size: 64
  val_batch_size: 64
  patch_size: 64
  num_workers: 8
  pin_memory: True

exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  manual_seed: 1265

trainer_params:
  devices: 1
  strategy: "ddp"
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "FlowVAE"
