model_params:
  name: "VanillaVAE"
  latent_dim: 4
  encoder:
    in_channels: 3
    base_dim: 8
    scales: 4
    num_blocks: 1
    channel_multiplier: 2
    residual: True
    bottleneck: True
    weight_norm: False
    norm: "layer"
    activation: "silu"
  decoder:
    out_channels: 3
    scales: 4
    num_blocks: 1
    channel_multiplier: 0.5
    residual: True
    bottleneck: True
    weight_norm: False
    norm: "layer"
    activation: "silu"
    final_activation: "sigmoid"

data_params:
  dataset: "celeba"
  data_path: "/mnt/ext-data-01/data"
  train_batch_size: 64
  val_batch_size: 64
  patch_size: 64
  num_workers: 4
  pin_memory: True

experiment_params:
  optim1:
    lr: 0.0005
    weight_decay: 0.0
    warmup_epochs: 5
    warmup_start_lr: 0.00005
    eta_min: 0.00005
  manual_seed: 1265
  max_epochs: 100
  test_latent_size: [4, 4]

trainer_params:
  devices: 1
  strategy: "ddp"
  precision: "32-true"
  gradient_clip_val: 5.0
  gradient_clip_algorithm: norm

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
