model_params:
  name: "VAEGAN"
  latent_dim: 4
  adversarial_weight: 0.5
  feature_matching_weight: 0
  encoder:
    in_channels: 3
    base_dim: 8
    scales: 4
    num_blocks: 1
    channel_multiplier: 2
    transpose: False
    kernel_size: 5
    residual: True
    bottleneck: True
    weight_norm: False
    norm: "layer"
    activation: "silu"
  decoder:
    out_dim: 3
    scales: 4
    num_blocks: 1
    channel_multiplier: 0.5
    transpose: True
    kernel_size: 5
    residual: True
    bottleneck: True
    weight_norm: False
    norm: "layer"
    activation: "silu"
    final_activation: "sigmoid"
  discriminator:
    in_channels: 3
    base_dim: 4
    out_dim: 1
    scales: 5
    num_blocks: 1
    channel_multiplier: 2
    transpose: False
    kernel_size: 5
    residual: True
    bottleneck: True
    weight_norm: False
    norm: "batch"
    activation: "silu"

data_params:
  dataset: "celeba"
  data_path: "/mnt/ext-data-01/data"
  train_batch_size: 64
  val_batch_size: 64
  patch_size: 64
  num_workers: 4
  pin_memory: True

experiment_params:
  optim1:
    submodel: generator
    lr: 0.0005
    weight_decay: 0.001
    warmup_epochs: 5
  optim2:
    submodel: discriminator
    lr: 0.0005
    weight_decay: 0.001
    warmup_epochs: 5
  manual_seed: 1265
  metrics: ["lpips", "ssim", "psnr", "fid"]
  clip_gradient: True
  gradient_clip_val: 5.0
  gradient_clip_algorithm: norm

trainer_params:
  devices: 1
  strategy: "ddp"
  precision: "32-true"
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "VAEGAN"
